language: python
python:
  - "2.7"
install:
  - pip install pandas
  - pip install matplotlib
  - pip install numpy
  - pip install scipy
  - pip install scikit-learn
  - pip install jinja2
script: nosetests
