language: python
python:
  - "2.7"
virtualenv:
  system_site_packages: true
before_install:
 - sudo apt-get install -qq python-numpy python-scipy
install:
  - pip install pandas
  - pip install matplotlib
  - pip install scikit-learn
  - pip install jinja2
script: nosetests -a '!slow'
